name: Run Tests

on:
  push:
    branches:
      - lab

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LAB branch
        uses: actions/checkout@v4
        with:
          ref: lab

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements_flask.txt

      - name: Run tests
        run: pytest

      - name: Dispatch Lambda workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: lambda.yml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch EC2 workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ec2.yml
          token: ${{ secrets.GITHUB_TOKEN }}